# Darcubox Color Palette
set -l foreground d0c6a5
set -l selection 404146
set -l comment 8f8682
set -l crimson d01c26
set -l gold fb982e
set -l sunshine ffd072
set -l lime 9cd750
set -l sand e6a96b
set -l sapphire 0f829d
set -l lilac cd80b9

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $sapphire
set -g fish_color_keyword $lilac
set -g fish_color_quote $sunshine
set -g fish_color_redirection $foreground
set -g fish_color_end $gold
set -g fish_color_error $crimson
set -g fish_color_param $sand
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selecion
set -g fish_color_operator $lime
set -g fish_color_escape $lilac
set -g fish_color_autosuggestion $comment

# Completion Pager Colors
set -g fish_pager_color_progress $comment
set -g fish_pager_color_prefix $sapphire
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
set -g fish_pager_color_selected_background --background=$selection
